version: '3'
services:
  php:
    image: sfidanza/lamp-backend
    volumes:
      - ../php-code/dagobah:/var/www/dagobah
      - ../php-code/euro/euro2008/src:/var/www/euro2008
      - ../php-code/euro/euro2012/src:/var/www/euro2012
      - ../php-code/euro/worldcup2010/src:/var/www/worldcup2010
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db

  db:
    image: sfidanza/lamp-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    restart: always

volumes:
  db-data: